CREATE TABLE dbo.PipelineLogs(
	Id INT IDENTITY(1,1) CONSTRAINT PK_Logs PRIMARY KEY
	,PipelineName VARCHAR(100) NOT NULL
	,ExecutionStart SMALLDATETIME NOT NULL
	,ExecutionEnd SMALLDATETIME NOT NULL
	,ExecutionDate SMALLDATETIME NOT NULL DEFAULT GETDATE()
	,Result BIT NOT NULL
)